### ISSUE TITLE
Show error in register

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/fe-next-hire-job#2]
I got error but not showing anything in your app

![Screenshot (136)](https://github.com/nluthfis/fe-next-hire-job/assets/49361887/33e5c9b2-3110-4be8-a740-debab61acfb4)

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/fe-next-hire-job/assets/42950482/523f66a9-8e41-469a-ab0d-a233a82cc781)
Fixed!

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 17 22" src="https://github.com/nluthfis/hire-job-web/assets/49361887/616a3590-f628-44e6-b456-acf3fd25f81c">

Done
