### ISSUE TITLE
candidate not found but already registered in list app

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/fe-next-hire-job#3]
![Screenshot (139)](https://github.com/nluthfis/fe-next-hire-job/assets/49361887/4cc663a3-4ad8-42a4-a6b0-98ee5f894c74)
![Screenshot (138)](https://github.com/nluthfis/fe-next-hire-job/assets/49361887/5f620f21-f217-4def-ba2e-71d1ac1cae38)

**Comment by nluthfis** [comment]
fixed

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 23 58" src="https://github.com/nluthfis/hire-job-web/assets/49361887/9b003858-5801-4eb7-b654-af77336dbc98">

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 24 14" src="https://github.com/nluthfis/hire-job-web/assets/49361887/bf87a8f8-fdf4-4571-a43d-6130484b3b4e">

**Comment by kubil-ismail** [comment]
done
