### ISSUE TITLE
Cannot find edit button in profile

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/fe-next-hire-job#4]
![Screenshot (139)](https://github.com/nluthfis/fe-next-hire-job/assets/49361887/158717f2-b977-4594-8e11-5eef2bf8e2cf)

**Comment by kubil-ismail** [comment]
Sorry wrong capture

![Screenshot (140)](https://github.com/nluthfis/fe-next-hire-job/assets/49361887/c78ea1ff-7c79-485d-93a7-041c38730486)

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/fe-next-hire-job/assets/42950482/8ccb366f-5eeb-4de9-8edd-6a9bd7b5fb5c)
fixed!

**Comment by kubil-ismail** [comment]
Done

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 21 22" src="https://github.com/nluthfis/hire-job-web/assets/49361887/93e41f66-22ca-44db-866b-458849f02efa">
